# Generated by Django 3.1 on 2020-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='city_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='sido_id',
            field=models.IntegerField(default=0),
        ),
    ]
