# Generated by Django 3.1 on 2020-08-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ootdapp', '0002_auto_20200819_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ootdapp.city'),
        ),
        migrations.AlterField(
            model_name='image',
            name='sido_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ootdapp.sido'),
        ),
    ]
