# Generated by Django 3.1 on 2020-08-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootdapp', '0003_auto_20200823_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=10),
        ),
    ]
